openapi: 3.0.0
info:
  title: AV Catalog Converter API
  description: API for converting and standardizing audio-visual equipment catalogs
  version: 1.0.0
  contact:
    name: Support
    email: support@example.com
servers:
  - url: http://localhost:8081
    description: Local development server
  - url: http://localhost:8080
    description: Alternative local server
  - url: https://api.example.com
    description: Production server
paths:
  /api/health:
    get:
      summary: Health check
      description: Check if the API is running and get basic information
      operationId: healthCheck
      responses:
        '200':
          description: Service is running properly
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  version:
                    type: string
                    example: 1.0.0
                  app_name:
                    type: string
                    example: AV Catalog Converter
                  llm_info:
                    type: object
                    properties:
                      model_id:
                        type: string
                        example: microsoft/phi-2
                      quantization:
                        type: string
                        example: 4bit
                      max_tokens:
                        type: integer
                        example: 1024
  /api/upload:
    post:
      summary: Upload file
      description: Upload a catalog file and save it for later processing. Returns a job ID that can be used to reference the uploaded file.
      operationId: uploadFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The catalog file to upload
                company:
                  type: string
                  description: Optional company name associated with the file
              required:
                - file
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: File uploaded successfully
                  job_id:
                    type: string
                    example: 550e8400-e29b-41d4-a716-446655440000
                  filename:
                    type: string
                    example: example_catalog.xlsx
        '400':
          description: Missing file or invalid format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '413':
          description: File too large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Processing error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/analyze:
    post:
      summary: Analyze file structure
      description: Analyze a catalog file's structure without fully processing it. You can either upload a new file or reference a previously uploaded file using a job_id. The response includes a job_id that should be used with the /api/map/{job_id} endpoint for the next step in the workflow.
      operationId: analyzeFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The catalog file to analyze (required if job_id is not provided)
                job_id:
                  type: string
                  description: Job ID from a previous upload (required if file is not provided)
                  example: "550e8400-e29b-41d4-a716-446655440000"
              oneOf:
                - required: [file]
                - required: [job_id]
      responses:
        '200':
          description: File analyzed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: File analyzed successfully
                  job_id:
                    type: string
                    example: 550e8400-e29b-41d4-a716-446655440000
                    description: Job ID to use with the /api/map/{job_id} endpoint for the next step
                  field_mappings:
                    type: object
                    description: Potential field mappings detected in the file
                  column_info:
                    type: object
                    description: Analysis of columns in the file
                  data_quality:
                    type: array
                    description: Data quality issues detected in the file
                    items:
                      type: object
                  structure:
                    type: object
                    properties:
                      row_count:
                        type: integer
                        example: 1000
                      column_count:
                        type: integer
                        example: 15
                      effective_rows:
                        type: integer
                        example: 950
                      data_rows:
                        type: integer
                        example: 950
        '400':
          description: Missing file or invalid job_id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: File not found for the provided job ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Analysis error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/map/{job_id}:
    post:
      summary: Map fields using job ID
      description: Map fields to standard schema using a previously analyzed file. This endpoint should be used after calling the /api/analyze endpoint, using the job_id returned from that call.
      operationId: mapFieldsWithJobId
      parameters:
        - name: job_id
          in: path
          required: true
          description: Job ID from a previous analyze operation
          schema:
            type: string
            example: "550e8400-e29b-41d4-a716-446655440000"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                mappings:
                  type: object
                  description: Optional user-specified mappings to override automatic mappings
                  example: {"Product Code": "SKU", "Description": "Short Description"}
      responses:
        '200':
          description: Fields mapped successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Fields mapped successfully
                  mapping_results:
                    type: object
                    description: Results of the mapping operation
                  sample_data:
                    type: array
                    items:
                      type: object
                    description: Sample of mapped data
                  missing_required:
                    type: array
                    items:
                      type: string
                    description: Required fields that could not be mapped
                  llm_stats:
                    type: object
                    description: Statistics about LLM usage during mapping
        '404':
          description: Invalid job ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Mapping error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
      required:
        - error
